"""
MCP Location Server

A Model Context Protocol server for geocoding addresses to coordinates.
Generated By: Cursor (Claude Sonnet 4)
"""

__version__ = "0.1.0"
__author__ = "MCP Playground"
__email__ = "nmalik@redhat.com"

__all__ = ["__version__", "__author__", "__email__"] 